# Generated by Django 5.0.4 on 2024-04-15 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_categorie_score_alter_note_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='oHn1mX6rX6nNitGC6obg27vskTf2uw', max_length=300),
        ),
        migrations.AlterField(
            model_name='note',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 11, 6, 16, 816467)),
        ),
    ]
